apiVersion: v1
kind: PersistentVolume
metadata:
  name: mongodb
  namespace: webshop-app
  labels:
    type: local
    app: mongodb
spec:
  # storageClassName: microk8s-hostpath
  capacity:
    storage: 5Gi
  accessModes:
    - ReadWriteMany
  hostPath:
    path: "/opt/mongodb/data"